# Generated by Django 6.0.3 on 2026-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', False)), fields=('reservation',), name='unique_order_per_reservation'),
        ),
    ]
